theme: jekyll-theme-minimal
title: helloWatt_- Jeedom plugin for Hello-Watt Acount
description: Jeedom plugin to retrieve gaz consumption from helloWatt website
show_downloads: true
logo: /assets/images/logo.png